apiVersion: v1
kind: Service
metadata:
  name: tempconv-grpc-service
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
spec:
  selector:
    app: tempconv-grpc
  ports:
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: 50051
  type: LoadBalancer
